# Generated by Django 4.2.6 on 2023-11-01 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False, verbose_name='ItemID')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('itemName', models.CharField(max_length=50, verbose_name='ItemName')),
                ('purchaseYear', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='PurchaseYear')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='物品价格')),
                ('item_photo', models.ImageField(blank=True, null=True, upload_to='images/item', verbose_name='ItemPhoto')),
                ('itemDesc', models.CharField(blank=True, max_length=200, null=True, verbose_name='ItemDesc')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('new_old_degree', models.IntegerField(choices=[(0, '旧'), (1, '较旧'), (2, '较新'), (3, '新')], verbose_name='新旧程度')),
                ('itemStatus', models.IntegerField(choices=[(0, '在售'), (1, '已售'), (2, '已被下架')], verbose_name='itemStatus')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.ordinaryuser', verbose_name='卖家')),
            ],
            options={
                'verbose_name': '物品信息',
                'verbose_name_plural': '物品信息',
                'db_table': 'item',
                'ordering': ['itemId'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单价格')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('order_status', models.IntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '已发货'), (3, '已送达')], default=0, verbose_name='订单状态')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to='User.ordinaryuser', verbose_name='买家')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.item', verbose_name='物品')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to='User.ordinaryuser', verbose_name='卖家')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'orders',
                'ordering': ['-order_time'],
            },
        ),
    ]
