# Generated by Django 4.2.6 on 2023-11-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False, verbose_name='管理员编号')),
                ('admin_name', models.CharField(max_length=20, verbose_name='管理员昵称')),
                ('admin_password', models.CharField(max_length=20, verbose_name='管理员密码')),
                ('admin_email', models.CharField(max_length=20, verbose_name='管理员邮箱')),
            ],
            options={
                'verbose_name': '管理员信息',
                'verbose_name_plural': '管理员信息',
                'db_table': 'Administrator',
                'ordering': ['admin_id'],
            },
        ),
        migrations.CreateModel(
            name='OrdinaryUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户昵称')),
                ('user_password', models.CharField(max_length=20, verbose_name='用户密码')),
                ('user_email', models.CharField(max_length=20, verbose_name='用户邮箱')),
                ('accountStatus', models.IntegerField(choices=[(1, '正常'), (0, '已封禁')], verbose_name='AccountStatus')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'OrdinaryUser',
                'ordering': ['user_id'],
            },
        ),
    ]
